export const data=[
    {
        id:1,
        title:"Menu",
        items:[{
            id:1,
            url:"/",
           icon:"/home.svg",
           title:"Home" 
        },
        {
            id:2,
            url:"/user/1",
            icon:"user.svg",
            title:"Profile"

        }
    ]
    },
    {
        id:2,
        title:"Lists",
        items:[{
            id:1,
            url:"/Users",
           icon:"/user.svg",
           title:"Users" 
        },{
            id:2,
            url:"/products",
            icon:"product.svg",
            title:"Products"
        },{
            id:3,
            url:"/orders",
            icon:"order.svg",
            title:"Orders"
        },{
            id:4,
            url:"/posts",
            icon:"post2.svg",
            title:"Posts"
        }
    ]
    },
    {
        id:3,
        title:"general",
        items:[
            {
                id:1,
                title:"Elements",
                url:"/",
                icon:"element.svg"
            },
            {
                id:2,
                title:"Notes",
                url:"/",
                icon:"note.svg"
            },
            {
                id:3,
                title:"Forms",
                url:"/",
                icon:"form.svg"
            }
        ]
    },
    {
        id:4,
        title:"Maintenance",
        items:[
            {
                id:1,
                title:"Settings",
                url:"/",
                icon:"setting.svg"
            },
            {
                id:2,
                title:"Backups",
                url:"/",
                icon:"backup.svg"
            },  
        ]
    },
    {
        id:5,
        title:"analytics",
        items:[{
            id:1,
            title:"Charts",
            url:"/",
            icon:"chart.svg"
        },
        {
            id:2,
            title:"Logs",
            url:"/",
            icon:"log.svg"
        }]
    }
]